
services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
        POSTGRES_USER: webapicourse
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: movies
    ports:
        - '5432:5432'

